### ISSUE TITLE
Uncaught exception reading temperature sensor

### ISSUE THREAD

**Issue by nathanprayzo** [brianfoshee/aquire#10]
If a temperature sensor is not connected to the board, the board would ideally assume a standard temperature and proceed to collect data from the sensors available.

Currently, if a temperature sensor is not connected to the board, an uncaught exception preventing the other sensors from being solicited.

```
open /sys/bus/w1/devices/28-031466321eff/id: no such file or directorypanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x14 pc=0x84944]

goroutine 1 [running]:
github.com/brianfoshee/raspberrypi/onewire.(*DS18S20).Read(0x0, 0x2, 0x2, 0x0, 0x0)
        /home/pi/go/src/github.com/brianfoshee/raspberrypi/onewire/ds18s20.go:80 +0x3c
main.main()
        /home/pi/go/src/github.com/brianfoshee/aquire/aquire.go:78 +0x8b0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:1322 +0x4

goroutine 5 [runnable]:
github.com/alexcesaro/statsd.func·005()
        /home/pi/go/src/github.com/alexcesaro/statsd/conn.go:66
created by github.com/alexcesaro/statsd.newConn
        /home/pi/go/src/github.com/alexcesaro/statsd/conn.go:78 +0x520
exit status 2
```

**Comment by nathanprayzo** [comment]
@brianfoshee You can now plug and unplug the temp sensor into the board while it's running. If no temp sensor is available on startup it will default to 77F, if the temp sensor is unplugged it will use the previous reading.

**Comment by brianfoshee** [comment]
nice!
